### ISSUE TITLE
NPM - Integrity checksum failed

### ISSUE THREAD

**Issue by wlensinas** [nomanHasan/todoapp-angular#2]
Hi there, I did the git clone and then when I tried the next command `npm install`, I get the next problem (extract from log that npm create):

> 10609 verbose stack Error: sha1-ZAM+20/NoIoyPnUztKGCDA8o0TA= integrity checksum failed when using sha1: wanted sha1-ZAM+20/NoIoyPnUztKGCDA8o0TA= but got sha1-4t0ikboUE/zKzY5c8Z8kkMv+Eqk=. (195194 bytes)
> 10609 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
> 10609 verbose stack     at Transform.emit (events.js:165:20)
> 10609 verbose stack     at endReadableNT (_stream_readable.js:1101:12)
> 10609 verbose stack     at process._tickCallback (internal/process/next_tick.js:152:19)
> 10610 verbose cwd /home/wlensinas/code/todoapp-angular
> 10611 verbose Linux 4.13.0-32-generic
> 10612 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> 10613 verbose node v9.4.0
> 10614 verbose npm  v5.6.0
> 10615 error code EINTEGRITY
> 10616 error sha1-ZAM+20/NoIoyPnUztKGCDA8o0TA= integrity checksum failed when using sha1: wanted sha1-ZAM+20/NoIoyPnUztKGCDA8o0TA= but got sha1-4t0ikboUE/zKzY5c8Z8kkMv+Eqk=. (195194 bytes)
> 10617 verbose exit [ 1, true ]

I tried this commands `npm cache verify` and `npm cache --force clean` and the problem persist.
[cncjs-issues 172](https://github.com/cncjs/cncjs/issues/172)

Any ideas?

PS: Thanks, the [first part](https://medium.com/netscape/mean-app-tutorial-with-angular-4-part-1-18691663ea96) of the project, it works!

**Comment by nomanHasan** [comment]
@wlensinas , I'm sorry I don't know why this error is occurring. Is your NodeJS and NPM installation up-to-date ? It seems that this error is NPM installation related. So you could try some other methods on people suggested in the cncjs issue.

You could also give the following method a try - 

`rm -rf node_modules`
`rm package-lock.json`
`rm -rf ~/.npm`
`npm install --update-binary --no-shrinkwrap`

If you solve it by some other way, please let me know da wae.
